version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_stock_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_user_pass
      POSTGRES_DB: pgstockdatabase
    ports:
      - "5432:5432"
    volumes:
      - pgstockdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: stock_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: db_user
      DB_PASSWORD: db_user_pass
      DB_NAME: pgstockdatabase
      FLASK_APP: flask_app/app.py
      FLASK_ENV: production
    ports:
         - "5000:5000"
    command: ["sh", "-c", "sleep 5 && flask run --host=0.0.0.0 --port=5000"]
#    command: [ "flask", "run", "--host=0.0.0.0" ]
#    command: ["python", "flask_app/app.py"]

volumes:
  pgstockdata:
