version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_stock_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_user_pass
      POSTGRES_DB: pgstockdatabase
    ports:
      - "5432:5432"
    volumes:
      - pgstockdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: stock_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: db_user
      DB_PASSWORD: db_user_pass
      DB_NAME: pgstockdatabase
    command: ["python", "novo.py"]

volumes:
  pgstockdata:
